In [1]:
%matplotlib qt

import scrapy
import logging
import json
import pandas as pd
from pandas import read_csv
import csv
import numpy as np
import ast
import logging
import os
import gensim
import logging
import smart_open
from sklearn.manifold import TSNE
import collections
import matplotlib.pyplot as plt
import scipy as sc

C:\Users\MStopa\AppData\Local\Continuum\anaconda3\envs\webscrape\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [2]:
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [3]:
# Set file names for train and test data
test_data_dir = os.path.join(gensim.__path__[0], 'test', 'test_data')
lee_train_file = os.path.join(test_data_dir, 'lee_background.cor')
lee_test_file = os.path.join(test_data_dir, 'lee.cor')
#startup_train_file=('CB_full.cor')
#startup_train_file=('startup.cor')
startup_train_file1=('finance.cor')
startup_train_file2=('hospitality.cor')
startup_train_file=('Finance_Hospitality_AI.cor')
startup_test_file=('startup_test.cor')
# print("test_data_dir",test_data_dir)

In [4]:
def read_corpus(fname, tokens_only=False):
    with smart_open.open(fname, encoding="iso-8859-1") as f:
        for i, line in enumerate(f):
            tokens = gensim.utils.simple_preprocess(line)
            if tokens_only:
                yield tokens
            else:
                # For training data, add tags
                yield gensim.models.doc2vec.TaggedDocument(tokens, [i])

def find_tokens(fname, token1):
    ia=[]
    with smart_open.open(fname, encoding="iso-8859-1") as f:
        for i, line in enumerate(f):
            if token1 in line:
                print("tinyML here:",i)
                ia.append(i)
                
    ianp=np.array(ia)
    return ianp


#train_corpus = list(read_corpus(lee_train_file))
#test_corpus = list(read_corpus(lee_test_file, tokens_only=True))
train_corpus=list(read_corpus(startup_train_file))
token1="federated"
ianp1=find_tokens(startup_train_file,token1)
print("ianp back",ianp1,ianp1.shape[0])
test_corpus=list(read_corpus(startup_test_file, tokens_only=True))
ianp2=find_tokens(startup_test_file,token1)
print("ianp back",ianp2)
print("len train corpus",len(train_corpus))
# print(test_corpus[:2])

tinyML here: 1147
tinyML here: 1276
ianp back [1147 1276] 2
ianp back []
len train corpus 1649


In [5]:
dim_vector=25
model = gensim.models.doc2vec.Doc2Vec(dm=1, vector_size=dim_vector, min_count=2, epochs=200)
model.build_vocab(train_corpus)
# print(f"Word 'penalty' appeared {model.wv.get_vecattr('penalty', 'count')} times in the training corpus.")
model.train(train_corpus, total_examples=model.corpus_count, epochs=model.epochs)
# vector = model.infer_vector(['only', 'you', 'can', 'prevent', 'forest', 'fires'])
# print(vector)

2021-07-28 12:07:03,289 : INFO : Doc2Vec lifecycle event {'params': 'Doc2Vec(dm/m,d25,n5,w5,mc2,s0.001,t3)', 'datetime': '2021-07-28T12:07:03.288434', 'gensim': '4.0.1', 'python': '3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]', 'platform': 'Windows-10-10.0.19041-SP0', 'event': 'created'}
2021-07-28 12:07:03,290 : INFO : collecting all words and their counts
2021-07-28 12:07:03,290 : INFO : PROGRESS: at example #0, processed 0 words (0/s), 0 word types, 0 tags
2021-07-28 12:07:03,373 : INFO : collected 24270 word types and 1649 unique tags from a corpus of 1649 examples and 506401 words
2021-07-28 12:07:03,373 : INFO : Creating a fresh vocabulary
2021-07-28 12:07:03,439 : INFO : Doc2Vec lifecycle event {'msg': 'effective_min_count=2 retains 14207 unique words (58.53728883395138%% of original 24270, drops 10063)', 'datetime': '2021-07-28T12:07:03.439229', 'gensim': '4.0.1', 'python': '3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.

2021-07-28 12:07:09,306 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:09,322 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:09,334 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:09,335 : INFO : EPOCH - 15 : training on 506401 raw words (407646 effective words) took 0.4s, 1068882 effective words/s
2021-07-28 12:07:09,695 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:09,695 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:09,709 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:09,710 : INFO : EPOCH - 16 : training on 506401 raw words (407864 effective words) took 0.4s, 1102799 effective words/s
2021-07-28 12:07:10,074 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:10,086 : INFO : worker thread finished; awaiting finish of 1 more thread

2021-07-28 12:07:16,714 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:16,715 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:16,722 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:16,724 : INFO : EPOCH - 35 : training on 506401 raw words (408050 effective words) took 0.4s, 1137595 effective words/s
2021-07-28 12:07:17,085 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:17,091 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:17,095 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:17,097 : INFO : EPOCH - 36 : training on 506401 raw words (407494 effective words) took 0.4s, 1100838 effective words/s
2021-07-28 12:07:17,453 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:17,454 : INFO : worker thread finished; awaiting finish of 1 more thread

2021-07-28 12:07:24,260 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:24,263 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:24,273 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:24,275 : INFO : EPOCH - 55 : training on 506401 raw words (407954 effective words) took 0.4s, 977351 effective words/s
2021-07-28 12:07:24,656 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:24,659 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:24,669 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:24,671 : INFO : EPOCH - 56 : training on 506401 raw words (407882 effective words) took 0.4s, 1041363 effective words/s
2021-07-28 12:07:25,081 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:25,085 : INFO : worker thread finished; awaiting finish of 1 more threads

2021-07-28 12:07:33,525 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:33,528 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:33,530 : INFO : EPOCH - 75 : training on 506401 raw words (407535 effective words) took 0.5s, 742044 effective words/s
2021-07-28 12:07:34,048 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:34,050 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:34,061 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:34,063 : INFO : EPOCH - 76 : training on 506401 raw words (407764 effective words) took 0.5s, 770257 effective words/s
2021-07-28 12:07:34,609 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:34,618 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:34,626 : INFO : worker thread finished; awaiting finish of 0 more threads


2021-07-28 12:07:42,310 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:42,311 : INFO : EPOCH - 95 : training on 506401 raw words (407796 effective words) took 0.4s, 1045156 effective words/s
2021-07-28 12:07:42,700 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:42,701 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:42,708 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:42,709 : INFO : EPOCH - 96 : training on 506401 raw words (407454 effective words) took 0.4s, 1030451 effective words/s
2021-07-28 12:07:43,097 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:43,099 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:43,106 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:43,108 : INFO : EPOCH - 97 : training on 506401 raw words (408037 effect

2021-07-28 12:07:50,315 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:50,317 : INFO : EPOCH - 115 : training on 506401 raw words (407931 effective words) took 0.4s, 1020411 effective words/s
2021-07-28 12:07:50,708 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:50,714 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:50,720 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:50,722 : INFO : EPOCH - 116 : training on 506401 raw words (407772 effective words) took 0.4s, 1017359 effective words/s
2021-07-28 12:07:51,109 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:51,111 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:51,117 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:51,119 : INFO : EPOCH - 117 : training on 506401 raw words (407409 eff

2021-07-28 12:07:58,320 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:58,322 : INFO : EPOCH - 135 : training on 506401 raw words (407663 effective words) took 0.4s, 1021614 effective words/s
2021-07-28 12:07:58,709 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:58,711 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:58,720 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:58,721 : INFO : EPOCH - 136 : training on 506401 raw words (407776 effective words) took 0.4s, 1030893 effective words/s
2021-07-28 12:07:59,106 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:07:59,107 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:07:59,116 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:07:59,116 : INFO : EPOCH - 137 : training on 506401 raw words (407935 eff

2021-07-28 12:08:06,628 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:08:06,629 : INFO : EPOCH - 155 : training on 506401 raw words (407650 effective words) took 0.4s, 1026231 effective words/s
2021-07-28 12:08:07,025 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:08:07,029 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:08:07,031 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:08:07,031 : INFO : EPOCH - 156 : training on 506401 raw words (407668 effective words) took 0.4s, 1023402 effective words/s
2021-07-28 12:08:07,440 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:08:07,443 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:08:07,454 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:08:07,455 : INFO : EPOCH - 157 : training on 506401 raw words (407882 eff

2021-07-28 12:08:14,747 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:08:14,748 : INFO : EPOCH - 175 : training on 506401 raw words (408006 effective words) took 0.4s, 1000557 effective words/s
2021-07-28 12:08:15,150 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:08:15,152 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:08:15,162 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:08:15,164 : INFO : EPOCH - 176 : training on 506401 raw words (408077 effective words) took 0.4s, 991292 effective words/s
2021-07-28 12:08:15,558 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:08:15,559 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:08:15,566 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:08:15,567 : INFO : EPOCH - 177 : training on 506401 raw words (407622 effe

2021-07-28 12:08:22,898 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:08:22,899 : INFO : EPOCH - 195 : training on 506401 raw words (407826 effective words) took 0.4s, 1023997 effective words/s
2021-07-28 12:08:23,296 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:08:23,299 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:08:23,300 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:08:23,302 : INFO : EPOCH - 196 : training on 506401 raw words (407632 effective words) took 0.4s, 1025113 effective words/s
2021-07-28 12:08:23,708 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-07-28 12:08:23,712 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-07-28 12:08:23,717 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-07-28 12:08:23,718 : INFO : EPOCH - 197 : training on 506401 raw words (407937 eff

In [6]:
ranks = []
second_ranks = []
color1=np.empty([len(train_corpus),3])

distance=np.zeros((len(train_corpus),len(train_corpus)))
print('len(color1)',len(color1),'\n len(model.dv)',len(model.dv))
inferred_vector_array=np.empty([len(train_corpus),dim_vector])
for doc_id in range(len(train_corpus)-1):
    inferred_vector = model.infer_vector(train_corpus[doc_id].words)
    inferred_vector_array[doc_id]=inferred_vector
    sims = model.dv.most_similar([inferred_vector], topn=len(model.dv))
    rank = [docid for docid, sim in sims].index(doc_id)
    ranks.append(rank)
    second_ranks.append(sims[1])

color1[0:437,0]=1.0
color1[0:437,1]=0.0
color1[0:437,2]=0.0
color1[437:886,0]=0.0
color1[437:886,1]=0.0
color1[437:886,2]=1.0
color1[886:,0]=0.0
color1[886:,1]=1.0
color1[886:,2]=0.0


np.nan_to_num(inferred_vector_array,copy=False)

# for i00 in range(len(train_corpus)):
#     for j00 in range(len(train_corpus)):
#         distance[i00,j00]=sc.spatial.distance.cosine(inferred_vector_array[i00],inferred_vector_array[j00])

# plt.figure(42,figsize=(15,13))
# plt.pcolormesh(distance,cmap='afmhot',vmin=0.80, vmax=0.85)
# plt.colorbar()
# plt.show(42)

ranks = []
second_ranks = []
for doc_id in range(len(train_corpus)):
    inferred_vector=model.infer_vector(train_corpus[doc_id].words)
    sims=model.dv.most_similar([inferred_vector], topn=len(model.dv))
    rank = [docid for docid,sim in sims].index(doc_id)
    ranks.append(rank)
    second_ranks.append(sims[1])
    
#    print('doc_id',doc_id,'sims',sims[0],sims[1],sims[2],sims[3],sims[4])
#     if sims[1][1] > 0.80:
#         print('\n doc_id',train_corpus[doc_id][0:10],'\n most like',train_corpus[sims[1][0]][0:10])

#    if "robot" in train_corpus[doc_id].words:


len(color1) 1649 
 len(model.dv) 1649


In [ ]:
X_embedded = TSNE(n_components=3,perplexity=50).fit_transform(inferred_vector_array)
# print('X_embedded',X_embedded)
X2=np.array(X_embedded)
# print('X2',X2)
print('color1',color1)
# plt.figure(44,figsize=(15,10))
fig = plt.figure(44)
ax = fig.add_subplot(111, projection = '3d')
X2_embeddedx=[]
X2_embeddedy=[]
X2_embeddedz=[]
for ii in range(ianp1.shape[0]):
    X2_embeddedx.append(X_embedded[ianp1[ii],0])
    X2_embeddedy.append(X_embedded[ianp1[ii],1])
    X2_embeddedz.append(X_embedded[ianp1[ii],2])

X2npx=np.array(X2_embeddedx)
X2npy=np.array(X2_embeddedy)
X2npz=np.array(X2_embeddedz)

# plt.scatter(X2npx,X2npy,s=250)
ax.scatter(X_embedded[:,0],X_embedded[:,1],X_embedded[:,2], marker='o', c = color1)
ax.set_xlim([-75,75])
ax.set_ylim([-75,75])
ax.set_zlim([-75,75])
plt.show(44)

color1 [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


C:\Users\MStopa\AppData\Local\Continuum\anaconda3\envs\webscrape\lib\site-packages\ipykernel_launcher.py:26: MatplotlibDeprecationWarning: Passing the block parameter of show() positionally is deprecated since Matplotlib 3.1; the parameter will become keyword-only in 3.3.


In [8]:
counter = collections.Counter(ranks)
print(counter)

Counter({0: 1614, 1: 24, 2: 4, 4: 3, 5: 1, 6: 1, 3: 1, 8: 1})
